- RedfishClientPkg/ConverterLib/src/RedfishCsCommon.c
allocateDuplicateStr() will not copy input string when input string is empty string. It returns NULL pointer and creates assertion in application driver.
Reviewed-by: Abner Chang <abner.chang@amd.com>
> RedfishClientPkg/ConverterLib: Fix empty string value issue

- RedfishClientPkg/ConverterLib/edk2library/Bios/v1_0_9/Lib.inf
- RedfishClientPkg/ConverterLib/edk2library/ComputerSystem/v1_5_0/Lib.inf
- RedfishClientPkg/ConverterLib/edk2library/ComputerSystemCollection/Lib.inf
- RedfishClientPkg/ConverterLib/edk2library/Memory/v1_7_1/Lib.inf
- RedfishClientPkg/ConverterLib/edk2library/MemoryCollection/Lib.inf
- RedfishClientPkg/Features/Bios/v1_0_9/Dxe/BiosDxe.c
- RedfishClientPkg/Features/ComputerSystem/v1_5_0/Dxe/ComputerSystemDxe.c
- RedfishClientPkg/Features/Memory/V1_7_1/Dxe/MemoryDxe.c
- RedfishClientPkg/Include/Protocol/EdkIIRedfishETagProtocol.h
- RedfishClientPkg/Library/EdkIIRedfishResourceConfigLib/EdkIIRedfishResourceConfigLib.c
- RedfishClientPkg/Library/RedfishAddendumLib/RedfishAddendumLib.c
- RedfishClientPkg/Library/RedfishFeatureUtilityLib/RedfishFeatureUtilityLib.c
- RedfishClientPkg/RedfishConfigLangMapDxe/RedfishConfigLangMapDxe.c
- RedfishClientPkg/RedfishETagDxe/RedfishETagDxe.c
V2:
Instead of modifying ConverterLib, use build option in INF file to fix build error
V1:
Fix RedfishClientPkg build errors and typos. The compiler toolchain is GCC5.
Signed-off-by: Nickle Wang <[nicklew@nvidia.com](mailto:nicklew@nvidia.com)>
Cc: Abner Chang <[abner.chang@amd.com](mailto:abner.chang@amd.com)>
Cc: Igor Kulchytskyy <[igork@ami.com](mailto:igork@ami.com)>
Reviewed-by: Abner Chang <abner.chang@amd.com>
> Fix RedfishClientPkg build errors

- .github/workflows/uncrustify-check.sh
Only run uncrustify check to c file and h file in script.
Signed-off-by: Nickle Wang <nicklew@nvidia.com>
> RedfishClientPkg/.github: fix uncrustify check error

- RedfishClientPkg/RedfishClientPkg.dsc
There are two problems with BaseSortLib reference: 1 BaseSortLib is the library instance name not the class name. 2 UefiSortLib instance from MdeModulePkg is also referenced below.
Let's use only one reference to SortLib.
While Redfish Client uses only quick sort for char* elements, UefiSortLib is preferred as it allows to sort DevicePath instances and wide strings.
Signed-off-by: Mike Maslenkin <mike.maslenkin@gmail.com>
Cc: Nickle Wang <nicklew@nvidia.com>
> Remove reference to BaseSortLib library

- RedfishClientPkg/Library/RedfishResourceIdentifyLibComputerSystem/v1_5_0/RedfishResourceIdentifyLibComputerSystem.c
- RedfishClientPkg/Library/RedfishResourceIdentifyLibComputerSystem/v1_5_0/RedfishResourceIdentifyLibComputerSystem.inf
- RedfishClientPkg/RedfishClientComponents.dsc.inc
This patch fixes misprint in name of a directory and its files. The name of these files should be RedfishResourceIdentifyLibComputerSystem as well as implemented library instance.
Cc: Nickle Wang <nicklew@nvidia.com>
> RedfishClientPkg: rename RedfishResourceIdentifyLibComuterSystem

- RedfishClientPkg/Include/Library/RedfishFeatureUtilityLib.h
- RedfishClientPkg/Library/RedfishFeatureUtilityLib/RedfishFeatureUtilityLib.c
Add function to validate Redfish request for string array type. There is case that user request invalid string array and feature driver can not find corresponding HII option.
Cc: Nick Ramirez <nramirez@nvidia.com>
> RedfishClientPkg/RedfishFeatureUtilityLib: validate string array

- RedfishClientPkg/Features/Bios/v1_0_9/Common/BiosCommon.c
- RedfishClientPkg/Features/ComputerSystem/v1_5_0/Common/ComputerSystemCommon.c
- RedfishClientPkg/Features/Memory/V1_7_1/Common/MemoryCommon.c
- RedfishClientPkg/Features/MemoryCollectionDxe/MemoryCollectionDxe.c
- RedfishClientPkg/RedfishFeatureCoreDxe/RedfishFeatureCoreDxe.c
fix misleading texts, fix format specifier
refine interaction with user about system reset
> fix traces

- RedfishClientPkg/RedfishFeatureCoreDxe/RedfishFeatureCoreDxe.c
- RedfishClientPkg/RedfishFeatureCoreDxe/RedfishFeatureCoreDxe.h
RedfishFeatureDriverStartup is callback function at TPL_CALLBACK level. In this function, Redfish events are signaled. However, Redfish events are created in TPL_CALLBACK level too. As the result, Redfish events cannot be invoked in desired sequence. Decrease the TPL to TPL_APPLICATION level inside RedfishFeatureDriverStartup and restore it to TPL_CALLBACK level before leaving this function. Now, Redfish events are called in correct sequence.
Cc: Nick Ramirez <nramirez@nvidia.com>
> RedfishClientPkg/RedfishFeatureCoreDxe: fix Redfish event issue.

- RedfishClientPkg/Features/Bios/v1_0_9/Dxe/BiosDxe.c
- RedfishClientPkg/Library/RedfishFeatureUtilityLib/RedfishFeatureUtilityLib.c
This patch set contains small fixes and the one major change related to Bios resources provisioning.
> Use POST for provisioning Bios attributes

- RedfishClientPkg/Features/Bios/v1_0_9/Dxe/BiosDxe.c
- RedfishClientPkg/Features/Bios/v1_0_9/Dxe/BiosDxe.inf
- RedfishClientPkg/Features/ComputerSystem/v1_5_0/Dxe/ComputerSystemDxe.c
- RedfishClientPkg/Features/ComputerSystem/v1_5_0/Dxe/ComputerSystemDxe.inf
- RedfishClientPkg/Features/ComputerSystemCollectionDxe/ComputerSystemCollectionDxe.c
- RedfishClientPkg/Features/ComputerSystemCollectionDxe/ComputerSystemCollectionDxe.inf
- RedfishClientPkg/Features/Memory/V1_7_1/Dxe/MemoryDxe.c
- RedfishClientPkg/Features/Memory/V1_7_1/Dxe/MemoryDxe.inf
- RedfishClientPkg/Features/MemoryCollectionDxe/MemoryCollectionDxe.c
- RedfishClientPkg/Features/MemoryCollectionDxe/MemoryCollectionDxe.inf
- RedfishClientPkg/Include/Library/RedfishFeatureUtilityLib.h
- RedfishClientPkg/Include/Library/RedfishHttpCacheLib.h
- RedfishClientPkg/Include/Library/RedfishVersionLib.h
- RedfishClientPkg/Include/RedfishCollectionCommon.h
- RedfishClientPkg/Include/RedfishResourceCommon.h
- RedfishClientPkg/Library/EdkIIRedfishResourceConfigLib/EdkIIRedfishResourceConfigLib.c
- RedfishClientPkg/Library/EdkIIRedfishResourceConfigLib/EdkIIRedfishResourceConfigLib.inf
- RedfishClientPkg/Library/RedfishFeatureUtilityLib/RedfishFeatureUtilityInternal.h
- RedfishClientPkg/Library/RedfishFeatureUtilityLib/RedfishFeatureUtilityLib.c
- RedfishClientPkg/Library/RedfishFeatureUtilityLib/RedfishFeatureUtilityLib.inf
- RedfishClientPkg/Library/RedfishHttpCacheLib/RedfishHttpCacheLib.c
- RedfishClientPkg/Library/RedfishHttpCacheLib/RedfishHttpCacheLib.inf
- RedfishClientPkg/Library/RedfishHttpCacheLib/RedfishHttpCacheLibInternal.h
- RedfishClientPkg/Library/RedfishVersionLib/RedfishVersionLib.c
- RedfishClientPkg/Library/RedfishVersionLib/RedfishVersionLib.inf
- RedfishClientPkg/RedfishClientLibs.dsc.inc
- RedfishClientPkg/RedfishClientPkg.dec
- RedfishClientPkg/RedfishClientPkg.dsc
Introduce RedfishHttpCacheLib to improve HTTP GET performance in Redfish feature drivers. Feature drivers often query same
Redfish resource multiple times for different purpose. Add HTTP cache mechanism to improve the performance.
Signed-off-by: Nickle Wang <nicklew@nvidia.com>
Cc: Nick Ramirez <nramirez@nvidia.com>
> RedfishClientPkg: introduce Redfish HTTP cache library

- RedfishClientPkg/Features/Bios/v1_0_9/Dxe/BiosDxe.c
- RedfishClientPkg/Features/BootOption/v1_0_4/Common/BootOptionCommon.c
- RedfishClientPkg/Features/BootOption/v1_0_4/Dxe/BootOptionDxe.c
- RedfishClientPkg/Features/ComputerSystem/v1_5_0/Dxe/ComputerSystemDxe.c
- RedfishClientPkg/Features/Memory/V1_7_1/Dxe/MemoryDxe.c
- RedfishClientPkg/Include/Library/RedfishFeatureUtilityLib.h
- RedfishClientPkg/Library/RedfishFeatureUtilityLib/RedfishFeatureUtilityLib.c
- RedfishClientPkg/Library/RedfishFeatureUtilityLib/RedfishFeatureUtilityLib.inf
- RedfishClientPkg/RedfishClientPkg.dec
Add PCD to disable ETag capability for the case Redfish service doesn't support ETag.
Cc: Nickle Wang <nicklew@nvidia.com>
Cc: Mike Maslenkin <mike.maslenkin@gmail.com>
Reviewed-by: Igor Kulchytskyy <igork@ami.com>
> RedfishClientPkg: Add ETag PCD and revise Redfish ETag functions

- RedfishClientPkg/Library/RedfishFeatureUtilityLib/RedfishFeatureUtilityLib.c
Third parameter of AsciiStrToUnicodeStrS is the number of character in destination buffer, not the size in byte of destination buffer. This creates failure of converting ASCII string to Unicode string in Redfish application while getting Location field in HTTP header.
Cc: Nick Ramirez <nramirez@nvidia.com>
> RedfishClientPkg/RedfishFeatureUtilityLib: fix wrong parameter issue

- RedfishClientPkg/ConverterLib/src/RedfishCsCommon.c
- RedfishClientPkg/RedfishFeatureCoreDxe/RedfishFeatureCoreDxe.c
The memory returned by json_dumps() must be freed.
Cc: Nickle Wang <nicklew@nvidia.com>
> RedfishClientPkg: fix memory leak in ConverterLib

- RedfishClientPkg/Features/Bios/v1_0_9/Common/BiosCommon.c
- RedfishClientPkg/Features/BootOption/v1_0_4/Common/BootOptionCommon.c
- RedfishClientPkg/Features/ComputerSystem/v1_13_0/Common/ComputerSystemCommon.c
- RedfishClientPkg/Features/ComputerSystem/v1_5_0/Common/ComputerSystemCommon.c
- RedfishClientPkg/Features/ComputerSystemCollectionDxe/ComputerSystemCollectionDxe.c
- RedfishClientPkg/Features/Memory/V1_7_1/Common/MemoryCommon.c
- RedfishClientPkg/Features/MemoryCollectionDxe/MemoryCollectionDxe.c
- RedfishClientPkg/Library/RedfishResourceIdentifyLibComputerSystem/v1_5_0/RedfishResourceIdentifyLibComputerSystem.c
This set contains fixes for proper deallocation of  the structures returned by JsonStructProtocol->ToStructure()
> Destroy structure leak

- RedfishClientPkg/Features/Bios/v1_0_9/Dxe/BiosDxe.c
- RedfishClientPkg/Features/BootOption/v1_0_4/Dxe/BootOptionDxe.c
- RedfishClientPkg/Features/ComputerSystem/v1_13_0/Dxe/ComputerSystemDxe.c
- RedfishClientPkg/Features/ComputerSystem/v1_5_0/Dxe/ComputerSystemDxe.c
- RedfishClientPkg/Features/Memory/V1_7_1/Dxe/MemoryDxe.c
Private->Uri is initialized after calling SetRedfishSettingsObjectsUri() but it is used in SetRedfishSettingsObjectsUri function. Use input parameter "Uri" instead.
> RedfishClientPkg/Features: Variable used before being initialized

- RedfishClientPkg/Library/RedfishFeatureUtilityLib/RedfishFeatureUtilityLib.c
When feature driver post data to Redfish service, Redfish service can respond with HTTP status code "201 Created" with "location" in HTTP response header. Add this case in GetHttpResponseEtag() and GetHttpResponseLocation() functions.
> RedfishClientPkg/RedfishFeatureUtilityLib: accept 201 HTTP status code

- .github/CODEOWNERS
- .github/pull_request_template.md
- README.md
Since edk2 and edk2-platform moved reviews to GitHub pull requests, we follow the same process and move edk2-redfish-clients reviews to GitHub pull requests.
- Add CODEOWNERS to automatically attach reviewer when pull request is created.
- Add pull request template to remind developer to add required information in pull request description.
- Update README.md.
> .github: Move review to GitHub pull request

- RedfishClientPkg/ConverterLib/src/Bios/Bios.V1_0_0/Bios.V1_0_0.c
- RedfishClientPkg/ConverterLib/src/Bios/Bios.V1_0_1/Bios.V1_0_1.c
- RedfishClientPkg/ConverterLib/src/Bios/Bios.V1_0_2/Bios.V1_0_2.c
- RedfishClientPkg/ConverterLib/src/Bios/Bios.V1_0_3/Bios.V1_0_3.c
- RedfishClientPkg/ConverterLib/src/Bios/Bios.V1_0_4/Bios.V1_0_4.c
- RedfishClientPkg/ConverterLib/src/Bios/Bios.V1_0_5/Bios.V1_0_5.c
- RedfishClientPkg/ConverterLib/src/Bios/Bios.V1_0_6/Bios.V1_0_6.c
- RedfishClientPkg/ConverterLib/src/Bios/Bios.V1_0_7/Bios.V1_0_7.c
- RedfishClientPkg/ConverterLib/src/Bios/Bios.V1_0_8/Bios.V1_0_8.c
- RedfishClientPkg/ConverterLib/src/Bios/Bios.V1_0_9/Bios.V1_0_9.c
- RedfishClientPkg/ConverterLib/src/Bios/Bios.V1_1_0/Bios.V1_1_0.c
- RedfishClientPkg/ConverterLib/src/Bios/Bios.V1_1_1/Bios.V1_1_1.c
- RedfishClientPkg/ConverterLib/src/Bios/Bios.V1_1_2/Bios.V1_1_2.c
- RedfishClientPkg/ConverterLib/src/Bios/Bios.V1_2_0/Bios.V1_2_0.c
CsJson in CS_To_JSON_Attributes() is a parameter from caller but it gets created by json_object() again. As the result, caller never get the JSON attributes generated in this function and causing the issue.
Tested on server platform
> RedfishClientPkg/ConverterLib: missing attributes

- RedfishClientPkg/Features/Bios/v1_0_9/Common/BiosCommon.c
- RedfishClientPkg/Features/ComputerSystemCollectionDxe/ComputerSystemCollectionDxe.c
- Add the function to detect the condition when BIOS loads default settings. In this case, feature driver should ignore the request at BMC side since they are stale settings. And feature driver should force update default settings to BMC.
- Code optimization for BIOS feature driver and minor bug fix.
Build pass on RedfishClinetPkg
> RedfishClientPkg/Feature: Default detection

- RedfishClientPkg/Features/Bios/v1_0_9/Common/BiosCommon.c
- RedfishClientPkg/Features/Bios/v1_0_9/Dxe/BiosDxe.inf
- RedfishClientPkg/Features/BootOption/v1_0_4/Common/BootOptionCommon.c
- RedfishClientPkg/Features/BootOption/v1_0_4/Dxe/BootOptionDxe.inf
- RedfishClientPkg/Features/ComputerSystem/v1_13_0/Common/ComputerSystemCommon.c
- RedfishClientPkg/Features/ComputerSystem/v1_13_0/Dxe/ComputerSystemDxe.inf
- RedfishClientPkg/Features/ComputerSystem/v1_5_0/Common/ComputerSystemCommon.c
- RedfishClientPkg/Features/ComputerSystem/v1_5_0/Dxe/ComputerSystemDxe.inf
- RedfishClientPkg/Features/Memory/V1_7_1/Common/MemoryCommon.c
- RedfishClientPkg/Features/Memory/V1_7_1/Dxe/MemoryDxe.inf
- RedfishClientPkg/Features/SecureBoot/v1_1_0/Common/SecureBootCommon.c
- RedfishClientPkg/Features/SecureBoot/v1_1_0/Dxe/SecureBootDxe.inf
- RedfishClientPkg/Include/Library/EdkIIRedfishResourceConfigLib.h
- RedfishClientPkg/Library/EdkIIRedfishResourceConfigLib/EdkIIRedfishResourceConfigInternal.h
- RedfishClientPkg/Library/EdkIIRedfishResourceConfigLib/EdkIIRedfishResourceConfigLib.c
- RedfishClientPkg/Library/EdkIIRedfishResourceConfigLib/EdkIIRedfishResourceConfigLib.inf
- RedfishClientPkg/RedfishClientPkg.dec
In current [EFI_REST_JSON_STRUCTURE_PROTOCOL design](https://uefi.org/specs/UEFI/2.10_A/31_EFI_Redfish_Service_Support.html#the-guidance-of-writing-efi-redfish-jsonstructure-converter), there is one-to-one mapping between Redfish schema version and Redfish feature driver. When BMC supports new Redfish schema version, the corresponding BIOS firmware update is required to include new feature driver. Otherwise, Redfish feature driver cannot find correct schema version support and entire UEFI Redfish function is failing. This creates trouble for firmware release management because BMC firmware and BIOS firmware are coupled together. And there is no guarantee that user will always update both two firmware together.
To decouple BMC firmware and BIOS firmware, we need a way to support newer …
> Redfish schema version forward compatibility support

- RedfishClientPkg/RedfishFeatureCoreDxe/RedfishFeatureCoreDxe.c
- RedfishClientPkg/RedfishFeatureCoreDxe/RedfishFeatureCoreDxe.h
- RedfishClientPkg/RedfishFeatureCoreDxe/RedfishFeatureCoreDxe.inf
Manageability status code is introduced to edk2 (https://github.com/tianocore/edk2/pull/6560). Add the ability to report Redfish communication failure via status code. This gives the chance for BMC to capture Redfish error.
When system reboot is required to apply Redfish changes, we also report it via status code. So, user is aware of this reboot.
- build pass
- tested on Arm based server
> RedfishClientPkg/RedfishFeatureCoreDxe: report failure via status code

- RedfishClientPkg/Features/Bios/v1_0_9/Common/BiosCommon.c
- RedfishClientPkg/Features/BootOptionCollection/BootOptionCollectionDxe.c
- RedfishClientPkg/Features/ComputerSystemCollectionDxe/ComputerSystemCollectionDxe.c
- RedfishClientPkg/Library/RedfishFeatureUtilityLib/RedfishFeatureUtilityLib.c
When system loads default and clear variables, feature driver should do a provision and push default values to BMC. And feature driver will ignore any pending settings because they are made based on stale settings.
However, instead of provision(), update() is called in feature driver. Update() may not push settings to BMC when BMC already has same settings.
Use provision() to force update default settings to BMC, so BMC has chance to reset resource like /Settings and /SD or attribute like ResetBiosToDefaultsPending.
- Build pass on RedfishClientPkg
- Tested on Arm based system.
> Default detection improvement

- RedfishClientPkg/Library/RedfishFeatureUtilityLib/RedfishFeatureUtilityLib.c
Fix incorrect format type. FeatureValue is CHAR8 string and the format type is %a instead of %s.
Build pass
> RedfishClientPkg/RedfishFeatureUtilityLib: incorrect format type

- RedfishClientPkg/HiiToRedfishBiosDxe/HiiToRedfishBiosData.h
StrCpyS resulting into crash because of  alignment issues, fixing this failure by removing #pragma pack(1) and use the default #pragma as per the build option, to align the string buffer to 16-bit boundary
Crash : ASSERT [HiiToRedfishBiosDxe] /edk2/MdePkg/Library/BaseLib/SafeString.c(234): ((UINTN)Destination & 0x00000001) == 0
Build passed : RedfishClientPkg
Bootup passed : Qemu (ArmVirtPkg) with RedfishClientPkg
> RedfishClientPkg: Fix to align string buffer

- RedfishClientPkg/Include/Library/RedfishSystemTopologyLib.h
- RedfishClientPkg/Library/RedfishSystemTopologyLibNull/RedfishSystemTopologyLibNull.c
- RedfishClientPkg/Library/RedfishSystemTopologyLibNull/RedfishSystemTopologyLibNull.inf
- RedfishClientPkg/RedfishClientLibs.dsc.inc
- RedfishClientPkg/RedfishClientPkg.dsc
Although the hardware information is currently published via SMBIOS or DeviceTree, not all information can be obtained from the above structure. Also, the above industry structure is not aligned with the Redfish schema. An abstract library and protocol for Redfish are necessary to abstract the different formats of hardware information. To provide flexibility to the platform implementation for obtaining the hardware information via the platform implementation-specific interface.
Introduce Redfish System Topology library and protocol to Redfish package to obtain the hardware component configuration information.
N/A
> Upstream system topology

- RedfishClientPkg/Readme.md
Add the description of the alternative Implementation of edk2 Redfish BIOS AttributeRegistry.
Add the description of alternative Implementation of
edk2 Redfish BIOS AttributeRegistry.
N/A
> RedfishClientPkg/Readme: Alternative AttirbuteRegistry Implementation
